apiVersion: v1
kind: Secret
metadata:
  name: autofs-config
type: Opaque
stringData:
  ## the username/password here must be a user than can access the automount share using CIFS
  user: TEST_USER
  password: TEST_PASSWORD